# Generated by Django 2.2.16 on 2021-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211009_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='можете загрузить картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
